#!/bin/sh

set -e

renice -19 $$ > /dev/null 2>&1 || true

exec gst-launch-0.10 udpsrc \
		port=4953 \
		multicast-group=239.0.0.1 \
	\! "audio/x-raw-int", \
		format=int, \
		rate=44100, \
		channels=2, \
		width=16, \
		depth=16 \
	\! alsasink
