.TH DUDLD 8 "14 Januar 2006" "Dudl Jukebox Daemon" "Version 0.1.9"
.SH NAME
dudld \- a mp3 jukebox daemon

.SH SYNOPSIS
.B dudld
[
.B \-?df
] [
.B \-p
.I port
] [
.B \-i
.I pid-file
] [
.B \-c
.I config
]
.SH DESCRIPTION
.B dudld
is the mp3 Jukebox commponent of the 
.B Dudl
Music Database.

It is designed to run just ontop of the music database and therefore lacks 
thorough editing capabilities for the DB.

.\" TODO: extend description

network oriented.

Dudld uses the dudld database.

Database is maintained elsewhere.

Gstreamer driven.

supports replaygain 
.BR http://replaygain.org/

.SH OPTIONS
Options available for the
.B dudld
command:
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable debug logging.
.TP
\fB\-f\fR, \fB\-\-foreground\fR 
Do not detach - stay in foreground.
.TP
\fB\-?\fR, \fB\-\-help\fR
A brief message.
.TP
\fB\-i\fR, \fB\-\-pidfile \fR\fIpid-file\fR
When dudld starts its process idenifier is written to
\fB\fIpid-file\fR. The likely default is 
\fB\fI/var/run/dudld/dudld.pid\fR.
.TP
\fB\-p\fR, \fB\-\-port=\fR\fIport\fR
Set the TCP port that dudld will listen to client connections. Default is
4445.
.TP
\fB\-c\fR, \fB\-\-config \fR\fIconfig\fR
Specify the config file to use. Default is 
\fB\fI/etc/dudld.conf\fR.
.SH FILES
.TP
.BI /etc/dudld.conf
dudld startup configuration
.TP
.BI /var/run/dudld/dudld.pid
.SH "SEE ALSO"
.BR Dudl::Overview (3),
.BR dudld.conf (5),
.BR dudlc (1),
.BR dcast-client (1)
.SH BUGS
I guess there are tons of 'em
.SH AUTHORS
Rainer Clasen
