#! /bin/sh
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
#
# This file was automatically customized by dh-make on Thu,  1 Aug 2002 18:35:50 +0200

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=dudld
DAEMON=/usr/sbin/$NAME
DESC="Dudl Jukebox daemon"

test -f $DAEMON || exit 0

set -e


flags=""
user=""
piddir=/var/run/$NAME
pidfile=$piddir/$NAME.pid

[ -r /etc/default/dudld ] && . /etc/default/dudld

if [ -n "$user" ]; then
	uarg="--chuid $user"
	export HOME=`getent passwd $user | cut -d : -f 6`
else
	uarg=""
	export HOME=`getent passwd root | cut -d : -f 6`
fi

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $piddir
	[ -n "$user" ] && chown -R $user $piddir
	start-stop-daemon --start --quiet --pidfile $pidfile \
		$uarg --exec $DAEMON -- $flags
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --oknodo --stop --quiet --pidfile $pidfile 
	echo "$NAME."
	;;
  restart|force-reload)
	echo "Restarting $DESC: ..."
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
