#! /bin/sh

### BEGIN INIT INFO
# Provides:          dudld
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dudld at boot time
# Description:       Enable dudld jukebox daemon at Startup.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=dudld
DAEMON=/usr/sbin/$NAME
DESC="Dudl Jukebox daemon"

test -f $DAEMON || exit 0

set -e

unset DISPLAY

flags=""
user=""
piddir=/var/run/$NAME
pidfile=$piddir/$NAME.pid

[ -r /etc/default/dudld ] && . /etc/default/dudld

if [ -n "$user" ]; then
	uarg="--chuid $user"
	export HOME=`getent passwd $user | cut -d : -f 6`
else
	uarg=""
	export HOME=`getent passwd root | cut -d : -f 6`
fi

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $piddir
	[ -n "$user" ] && chown -R $user $piddir
	start-stop-daemon --start --quiet --pidfile $pidfile \
		-N -19 $uarg --exec $DAEMON -- $flags
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --oknodo --stop --quiet --pidfile $pidfile 
	echo "$NAME."
	;;
  restart|force-reload)
	echo "Restarting $DESC: ..."
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
